### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by shariffaraz** [karanpratapsingh/react-native-boilerplate#13]
Hi
Whenever I try to run the boilerplate app it crashes on launch and I get this error. One thing I want to mention is that I renamed the project using the command given
```
java.lang.RuntimeException: Unable to instantiate application com.azure.likwid.MainApplication: java.lang.ClassNotFoundException: Didn't find class "com.azure.likwid.MainApplication" on path: DexPathList[[zip file "/data/app/com.azure.likwid-URAFleINvGHzepPn_4470Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.azure.likwid-URAFleINvGHzepPn_4470Q==/lib/arm64, /data/app/com.azure.likwid-URAFleINvGHzepPn_4470Q==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1296)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6830)
        at android.app.ActivityThread.access$1400(ActivityThread.java:268)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1982)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7811)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.azure.likwid.MainApplication" on path: DexPathList[[zip file "/data/app/com.azure.likwid-URAFleINvGHzepPn_4470Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.azure.likwid-URAFleINvGHzepPn_4470Q==/lib/arm64, /data/app/com.azure.likwid-URAFleINvGHzepPn_4470Q==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
        at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:47)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1156)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1288)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6830) 
        at android.app.ActivityThread.access$1400(ActivityThread.java:268) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1982) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:7811) 
```

**Comment by shariffaraz** [comment]
So I found out that somehow renaming the application actually removes the MainActivity.java and MainApplication.java. Brought them back and everything works fine now

**Comment by karanpratapsingh** [comment]
When you change the package name, make sure to make changes to folder structure as well so that it mirrors your package name, seems like you fixed it, awesome
